# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161213_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='nick',
        ),
    ]
