# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161213_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nick',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
