# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_comment_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=256)),
                ('pswd', models.CharField(max_length=256)),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
